lab_4/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.http import HttpResponse
from django.urls import path

from . import views
from lab_4 import views as appViews

app_name = 'lab_4'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/', appViews.index),
    url(r'^about/', appViews.about),
    url(r'^contact/', appViews.contact),
    url(r'^registration/', appViews.registration),
    url(r'^schedule/delete/', appViews.delete, name="delete"),
    url(r'^schedule/', appViews.schedule),
    url(r'^status/delete1/', appViews.delete1, name="delete1"),
    url(r'^status/', appViews.status),
    url(r'^books/$', appViews.book),
    url(r'^$', appViews.index),
    url(r'^books/api/books/(?P<search>\w+)/$', appViews.book_data),
    url(r'^subscribe/$', appViews.Subscribe_Views),
    url(r'^subscribe/check_email/$', appViews.check_email),
    # url(r'^get-subs-list/$', appViews.subs_list_json),
    # url(r'^subscribe/delete/$', appViews.unsubscribe),

]

ppw/urls.py
from django.contrib import admin
from django.urls import path, include


# from lab_4 import views as appViews
import lab_4.urls as lab_4

urlpatterns = [
	path(r'', include((lab_4, lab_4), namespace='lab_4')),
    # path(r'^$', include('lab_4'))
]

lab_4/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime

class Schedule(models.Model):
	judul = models.CharField(max_length = 50)
	day = models.DateField();
	time = models.TimeField();
	activity = models.CharField(max_length = 50)
	place = models.CharField(max_length = 50)
	category = models.CharField(max_length = 50)
	
	def __str__(self):
		return "{}".format(self.judul)

class Status(models.Model):
	judul = models.CharField(max_length = 300)
	isiJudul = models.CharField(max_length = 300)
	def __str__(self):
		return "{}".format(self.judul)

class Subscribe(models.Model):
	email = models.EmailField()
	nama = models.CharField(max_length=150)
	password1 = models.CharField(max_length=100)

	def as_dict(self):
		return{
			"email" : self.email,
			"nama" : self.nama,
			"password1" : self.password1,
		}

	def __str__(self):
		return "{}".format(self.email)

lab_4/forms.py
from django import forms
from django.forms import ModelForm
from lab_4.models import Schedule
from lab_4.models import Status
from lab_4.models import Subscribe

class scheduleForm(forms.ModelForm):
	class Meta:
		model = Schedule
		fields = ['judul','day','time','activity','place', 'category']
		widgets = {
			'judul': forms.TextInput(attrs={'class' : 'form-control'}),
			'day': forms.TextInput(attrs={'type':'date','class' : 'form-control'}),
			'time': forms.TextInput(attrs={'type':'time', 'class': 'form-control'}),
			'activity': forms.TextInput(attrs={'class': 'form-control'}),
			'place': forms.TextInput(attrs={'class': 'form-control'}),
			'category': forms.TextInput(attrs={'class': 'form-control'}),
		}
		label = {
			'judul': 'Judul',
			'day': 'Day',
			'time': 'Time',
			'activity': 'Activity',
			'place': 'Place'
		}

class statusForm(forms.ModelForm):
	class Meta:
		model = Status
		fields = ['judul','isiJudul']
		widgets = {
			'judul': forms.TextInput(attrs={'class' : 'form-control'}),
			'isiJudul': forms.TextInput(attrs={'class' : 'form-control'}),
		}

		label = {
			'judul': 'Judul',
			'isiJudul': 'Isi Judul'
		}


class subscribeForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = Subscribe
        fields = ["email","nama","password1"]

lab_4/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Schedule
from .forms import scheduleForm
from .models import Status
from .forms import statusForm
from .models import Subscribe
from .forms import subscribeForm
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.http import JsonResponse
import urllib.request, json
import requests
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.core import serializers
from django.db import IntegrityError
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages

def index(request):
    return render(request, 'Home.html')

def about(request):
    return render(request, 'About.html')

def contact(request):
    return render(request, 'Contact.html')

def registration(request):
    return render(request, 'Registration.html')

def schedule(request):
	posted = Schedule.objects.all()
	if request.method == 'POST':
		form = scheduleForm(request.POST)
		if form.is_valid():

			form.save()
			form = scheduleForm()

			context = {
				'Posts' : posted,
				'scheduleForm' : form,
			}
			return render(request, 'Schedule.html', context)

	else :
		
		form = scheduleForm()
		context = {
		'Posts': posted,
		'scheduleForm' : form,
		}
	return render(request,'Schedule.html', context)

def status(request):
	posted = Status.objects.all()
	if request.method == 'POST':
		form = statusForm(request.POST)
		if form.is_valid():

			form.save()
			form = statusForm()

			context = {
				'Posts' : posted,
				'statusForm' : form,
			}
			return render(request, 'Status.html', context)

	else :
		
		form = statusForm()
		context = {
		'Posts': posted,
		'statusForm' : form,
		}
	return render(request,'Status.html', context)

def delete(request):
	s= Schedule.objects.all().delete()
	print("Sdsiofljshduof")
	print(s)
	return redirect('/schedule')


def delete1(request):
	t= Status.objects.all().delete()
	print("Sdsiofljshduof")
	print(t)
	return redirect('/status')


def book_data(request,search):

	raw_data = requests.get('https://www.googleapis.com/books/v1/volumes?q='+ search).json()
	return JsonResponse(raw_data)

def book(request):
	return render(request, 'Books.html')

@csrf_exempt
def Subscribe_Views(request):
	all_subs = Subscribe.objects.all()
	subs_list = Subscribe.objects.all()
	if request.method == "POST":
		form = subscribeForm(request.POST)
		if form.is_valid():
			form_item = form.save(commit=True)
			form_item.save()
			form = subscribeForm()
	else:
		form = subscribeForm()
		
	return render(request, 'Subscribe.html', {'form' : form, 'subs_list' : subs_list})

@csrf_exempt
def check_email(request):
	if request.method == 'POST':
		email = request.POST['email']
		nama = request.POST['nama']
		password1 = request.POST['password1']

		subs_filter = Subscribe.objects.filter(email = email)

		if len(subs_filter) > 0 :
			return JsonResponse({'message' : 'Email already used'})

		else:
			return JsonResponse({'message' : 'User Valid'})

	else:
		return JsonResponse({'message' : 'Something went wrong'})

lab_4/templates/About.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- PAGE settings -->
  <link rel="icon" href="https://templates.pingendo.com/assets/Pingendo_favicon.ico">
  <title>About</title>
  <meta name="author" content="Pingendo">
  <!-- CSS dependencies -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <!-- <link rel="stylesheet" href="colorful.css" type="text/css"> -->
  <link rel="stylesheet" type= "text/css" href="{% static 'colorful.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<style>
.accordion {
    background-color: #eee;
    color: #444;
    cursor: pointer;
    padding: 18px;
    width: 100%;
    border: none;
    text-align: left;
    outline: none;
    font-size: 15px;
    transition: 0.4s;
}

.active, .accordion:hover {
    background-color: #ccc;
}

.accordion:after {
    content: '\002B';
    color: #777;
    font-weight: bold;
    float: right;
    margin-left: 5px;
}

.active:after {
    content: "\2212";
}

.panel {
    padding: 0 18px;
    background-color: white;
    max-height: 0;
    overflow: hidden;
    transition: max-height 0.2s ease-out;
}

@import url('https://fonts.googleapis.com/css?family=Open+Sans:400,700');

*{
  box-sizing:border-box;
}
body{
  margin:0;
  padding:0;
  font-size:16px;
  line-height:1.5;
}
.fullcontainer{
  width:100%;
  height:auto;
  font-family: 'Open Sans', sans-serif;
  padding:10% 8%;
}
.fullcontainer h2{
  margin:0;
  padding:0;
  color:#86C232;
  font-size:2.5rem;
  line-height:1.3;
}
.fullcontainer p{
  
}
.loadingpage{
  width:100vw;
  height:100vh;
  background:#161616;
  font-family: 'Open Sans', sans-serif;
  position:fixed;
  z-index:1;
  overflow:hidden;
}
.loadingpage::before{
  content:'';
  width:51%;
  height:100%;
  // background:yellow;
  background:#4a4c45;
  position:absolute;
  z-index:2;
  left:0%;
  top:0%;
}
.loadingpage::after{
  content:'';
  width:51%;
  height:100%;
  // background:blue;
  background:#4a4c45;
  position:absolute;
  z-index:2;
  right:0%;
  top:0%;
}
.loadingpage .counter{
  margin:auto;
  position:absolute;
  top:50%;
  left:50%;
  transform:translate(-50%,-50%);
  z-index:3;
}
.loadingpage h1{
  margin:0;
  padding:0;
  // color:grey;
  color:white;
  font-size:5rem;
  font-weight:bolder;
}
/******** when page is loaded **********/
.pageisloaded{
  visibility:hidden;
  //opacity:0;
  pointer-events:none;
  transform:translateY(-100%);
  transition:transform 0.5s 0.5s ease-out;
}
.pageisloaded::before{
  content:'';
  transform:translateX(-100%);
  transition:all 0.5s 0.5s cubic-bezier(0.645, 0.045, 0.355, 1.000);
}
.pageisloaded::after{
  content:'';
  transform:translateX(100%);
  transition:all 0.5s 0.5s cubic-bezier(0.645, 0.045, 0.355, 1.000);
}
.pageisloaded .counter{
  opacity:0;
  transition:all 0.5s ease-out;
}
@media screen and (max-width:400px){
  .fullcontainer h2{
    line-height:1.2;
    font-size:1.95rem;
  }
  .fullcontainer p{
    font-size:0.91rem;
  }
}

</style>
</head>

<div class="loadingpage">
  <div class="counter">
    <h1>0</h1>
  </div>
</div>

<body>
  <div class="px-0 bg-dark">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="nav nav-pills">
            <li class="nav-item bg-dark"> <a href="\index" class="nav-link"> <i class="fa fa-home fa-home"></i>&nbsp;Home</a> </li>
            <li class="nav-item text-info bg-dark" style=""> <a class="nav-link active" href="\about">About</a> </li>
            <li class="nav-item bg-dark"> <a href="\contact" class="nav-link">Contact</a> </li>
            <li class="nav-item bg-dark"> <a href="\registration" class="nav-link">Registration</a> </li>
            <li class="nav-item bg-dark"> <a href="\schedule" class="nav-link">Schedule</a> </li>
            <li class="nav-item bg-dark"> <a href="\status" class="nav-link">Status</a> </li>
            <li class="nav-item bg-dark"> <a href="\books" class="nav-link">Books</a> </li>
            <li class="nav-item bg-dark"> <a href="\subscribe" class="nav-link">Subscribe</a> </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <input type="button" id="change_background" value="Blue" margin />
  <input type="button" id="change_background2" value="White" />
  <div class="py-5 border-0">

    <div class="container">
      

      <div class="row">
      
      
      
        <h1>My Life</h1>

        <button class="accordion">Activities</button>
        <div class="panel">
          <p>I didn't really have much activities on campus besides from meeting my friends and learning, obviously. I usually learn, and then when lunchtime break is on, i meet my friends at a place called "gardu". Then after that i continue to learn as usual.</p>
        </div>

        <button class="accordion">Experience in Organization</button>
        <div class="panel">
          <p>I have little to none experience in terms of organization, and that's probably one thing that i regretted the most. Probably the most organization experience that i have is i joined SBF, its an acronym for Sekolah BEM Fasilkom, basically you became an intern to the Fasilkom's executive body. I joines the Sport section, or in bahasa you call it "Depor" Although it wasn't long, i really have a great time there.</p>
        </div>

        <button class="accordion">Achievements</button>
        <div class="panel">
          <p>I have no achievements in my time at Fasilkom. Hopefully in the near future i can have my own achievements and make me and also Fasilkom proud.</p>
        </div>

        <div class="px-lg-5 d-flex flex-column justify-content-center col-lg-6">
          <h2>About me</h2>
          <p class="mb-3 lead">My name is Muhammad Fathriza Zakeeffa Kusuma. I was born in Jakarta, on the 9th of October 2000. I am the youngest of my 3 brothers. People like to call me "Jija" or "Riza".</p>
        </div>
        <div class="col-lg-6"> <img class="img-fluid d-block" src="https://image.ibb.co/dCGrU9/205063_1007591039269_1663_n.jpg" width="350" height="400"data-toggle="tooltip" title="This is a picture of me when i was a little"> </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="d-flex flex-column justify-content-center p-3 col-lg-6">
          <p class="lead mb-0">I started my elementary school at Al-Azhar Syifa Budi Kemang. After that, i pursue my Junior Highschool at Labschool Kebayoran, followed by Garuda Cendekia Highschool. Right now i am a student in the Faculty of Computer Science, University of Indonesia.</p>
        </div>
        <div class="p-0 col-lg-5"> <img class="img-fluid d-block" src="https://image.ibb.co/knKZhU/Screen_Shot_2018_09_19_at_11_18_23_PM.png" data-toggle="tooltip" title="This is a picture of me and my family"> </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="px-lg-5 d-flex flex-column justify-content-center col-lg-6">
          <p class="mb-3 lead">I dont have a lot of activity outside being a student. My hobby includes playing computer and Playstation. Sometime i also play football with my friends.</p>
        </div>
        <div class="col-lg-6"> <img class="img-fluid d-block float-right" src="https://image.ibb.co/cMLJ99/Screen_Shot_2018_09_19_at_11_26_18_PM.png" data-toggle="tooltip" title="This is a picture of me and my best friends"> </div>
      </div>
    </div>
  </div>
  <script src="http://code.jquery.com/jquery-3.2.1.js" integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  <script>
  $(document).ready(function(){
      $('[data-toggle="tooltip"]').tooltip();   
  });
  </script> 


<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight){
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    } 
  });
}
</script>

<script type='text/javascript'
  src='http://code.jquery.com/jquery-1.11.0.js'></script>
<script type='text/javascript'>
$(window).load(function(){
    $( "#change_background" ).on( "click", function() {
        $("body").first().css("background-color","LightSkyBlue  ");
    });
});
</script>

<script type='text/javascript'
  src='http://code.jquery.com/jquery-1.11.0.js'></script>
<script type='text/javascript'>
$(window).load(function(){
    $( "#change_background2" ).on( "click", function() {
        $("body").first().css("background-color","White");
    });
});
</script>

<script>
  $(document).ready(function() {
  var counter = 0;
  function updateCounter(){
    if(counter == 11){
      clearInterval(foo);
      $('.loadingpage').addClass("pageisloaded");
    }
    else{
      $('.counter h1').html(counter);
      counter++;
    }
  }
  
  var foo = setInterval(updateCounter , 50);
  
});
</script>
</body>

</html>

lab_4/templates/Contact.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- PAGE settings -->
  <link rel="icon" href="https://templates.pingendo.com/assets/Pingendo_favicon.ico">
  <title>Contact</title>
  <meta name="description" content="Riza's Website">
  <meta name="keywords" content="Riza's Website">
  <!-- CSS dependencies -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <!-- <link rel="stylesheet" href="colorful.css"> -->
  <link rel="stylesheet" type= "text/css" href="{% static 'colorful.css' %}">
  <!-- Script: Navbar on-top -->
  <script src="js/navbar-ontop.js"></script>
</head>

<body>
  <div class="bg-dark">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="nav nav-pills">
            <li class="nav-item"> <a href="\index" class="nav-link"> <i class="fa fa-home fa-home"></i>&nbsp;Home</a> </li>
            <li class="nav-item"> <a class="nav-link" href="\about">About</a> </li>
            <li class="nav-item"> <a href="\contact" class="nav-link active">Contact</a> </li>
            <li class="nav-item"> <a href="\registration" class="nav-link">Registration</a> </li>
            <li class="nav-item bg-dark"> <a href="\schedule" class="nav-link">Schedule</a> </li>
            <li class="nav-item bg-dark"> <a href="\status" class="nav-link">Status</a> </li>
            <li class="nav-item bg-dark"> <a href="\books" class="nav-link">Books</a> </li>
            <li class="nav-item bg-dark"> <a href="\subscribe" class="nav-link">Subscribe</a> </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5 filter-dark cover bg-fixed" style="background-image: url('https://preview.ibb.co/chzE3V/planes.jpg');background-position:center bottom;background-size:cover;" id="mission">
    <div class="container my-auto">
      <div class="row">
        <div class="col-md-8 p-3 text-white" style="">
          <h2 class="mb-4">Contact me</h2>
          <p class="lead"><i>Phone +62 812 9618 2013<br>Email rkusumaa@yahoo.com</i>&nbsp;</p>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <!-- Script: Smooth scrolling between anchors in the same page -->
  <script src="js/smooth-scroll.js"></script>
  
</body>

</html>

lab_4/templates/Schedule.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- PAGE settings -->
  <link rel="icon" href="https://templates.pingendo.com/assets/Pingendo_favicon.ico">
  <title>Schedule</title>
  <meta name="description" content="Riza's Website">
  <meta name="keywords" content="Pingendo smke free template bootstrap 4">
  <!-- CSS dependencies -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <!-- <link rel="stylesheet" href="colorful.css"> -->
  <link rel="stylesheet" type= "text/css" href="{% static 'colorful.css' %}">
  <!-- Script: Navbar on-top -->
  <script src="js/navbar-ontop.js"></script>
</head>
<body style="background-color: black">
	<div class="p-0 bg-dark">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="nav nav-pills">
            <li class="nav-item"> <a href="\index" class="nav-link"> <i class="fa fa-home fa-home"></i>&nbsp;Home</a> </li>
            <li class="nav-item"> <a class="nav-link" href="\about">About</a> </li>
            <li class="nav-item"> <a href="\contact" class="nav-link">Contact</a> </li>
            <li class="nav-item"> <a href="\registration" class="nav-link">Registration</a> </li>
            <li class="nav-item bg-dark"> <a href="\schedule" class="nav-link active">Schedule</a> </li>
            <li class="nav-item bg-dark"> <a href="\status" class="nav-link">Status</a> </li>
            <li class="nav-item bg-dark"> <a href="\books" class="nav-link">Books</a> </li>
            <li class="nav-item bg-dark"> <a href="\subscribe" class="nav-link">Subscribe</a> </li>
          </ul>
        </div>
      </div>
    </div>
  </div>	
	<h1 style="background-color: Tomato; color:white; padding: 7%; font-size: 300%">Form data</h1><br>
	<div class="py-5">
		<div class ="container my-5">
			<div class ="row">
				<div class= "col-md-1"></div>
				<div class= "col-md-1"></div>
				<div class= "col-md-1"></div>
				<div class="col-md-2"></div>
					
	<form action="/schedule/" method="post" class="text-white" >
		{% csrf_token %}
		{{scheduleForm}}
		<button type="submit" class="btn btn-primary ">Submit</button>
		<a class="btn btn-danger" href= "{% url 'lab_4:delete' %}"> Delete</a>
	</div>
	</form>
	
	 


	{% for post in Posts %}
		<h3 style="color: white; background-color: DodgerBlue;">{{post.judul}}</h3>
		<p style="color: white">{{post.day}}</p>
		<p style="color: white">{{post.time}}</p>
		<p style="color: white">{{post.activity}}</p>
		<p style="color: white">{{post.place}}</p>
		<p style="color: white">{{post.category}}</p>
	{% endfor %}

</body>
</html>

lab_4/templates/Status.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- PAGE settings -->
  <link rel="icon" href="https://templates.pingendo.com/assets/Pingendo_favicon.ico">
  <title>Status</title>
  <meta name="description" content="Riza's Website">
  <meta name="keywords" content="Pingendo smke free template bootstrap 4">
  <!-- CSS dependencies -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <!-- <link rel="stylesheet" href="colorful.css"> -->
  <link rel="stylesheet" type= "text/css" href="{% static 'colorful.css' %}">
  <!-- Script: Navbar on-top -->
  <script src="js/navbar-ontop.js"></script>
</head>
<body style="background-color: black">
	<div class="p-0 bg-dark">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="nav nav-pills">
            <li class="nav-item"> <a href="\index" class="nav-link"> <i class="fa fa-home fa-home"></i>&nbsp;Home</a> </li>
            <li class="nav-item"> <a class="nav-link" href="\about">About</a> </li>
            <li class="nav-item"> <a href="\contact" class="nav-link">Contact</a> </li>
            <li class="nav-item"> <a href="\registration" class="nav-link">Registration</a> </li>
            <li class="nav-item bg-dark"> <a href="\schedule" class="nav-link">Schedule</a> </li>
            <li class="nav-item bg-dark"> <a href="\status" class="nav-link active">Status</a> </li>
            <li class="nav-item bg-dark"> <a href="\books" class="nav-link">Books</a> </li>
            <li class="nav-item bg-dark"> <a href="\subscribe" class="nav-link">Subscribe</a> </li>
          </ul>
        </div>
      </div>
    </div>
  </div>	
	<h1 style="color: White">Hi! How are you doing?</h1>
	
	  <form action="/status/" method="post" class="text-white" >
		{% csrf_token %}
		{{statusForm}}
		<button type="submit" class="btn btn-primary ">Submit</button>
	  <a class="btn btn-danger" style="color: white" href= "{% url 'lab_4:delete1' %}" > Delete</a>
	  <br>
	  <br>

	  {% for post in Posts %}
		<h3 style="color: white; background-color: DodgerBlue;">{{post.judul}}</h3>
		<p style="color: white">{{post.isiJudul}}</p>
	{% endfor %}

</body>
</html>